### ISSUE TITLE
6. Filtering the item list by ‘destroyed’ doesn’t show all destroyed items

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#1058]
This issue should be resolved, since VAL isn't showing accurate results.

Steps to reproduce:
- login to mock instance
- view `All items`
- add filter for `Destroyed`
- only one item is shown

But, from SQLite it's clear that items 2 and 2019 have been destroyed.

I checked the `network` tab. It's showing strange behaviour.  There is a call to `richItems` that gets the two rows back. Then there is another call, which just gets the single one we see.

**Comment by TahaKhanAbdalli** [comment]
Hello @IanMayo, 
Basically, this is not the issue. The reason the second destroyed item wasn't displaying is due to its date format, as stored in the `database`. When an item is destroyed, the destruction date format saved in the database appears as follows: `2024-03-22T11:25:59.794Z`. However, the destruction date format of item 2 which save in `database` is `2023-09-23 14:00:00` (with space)  after that we `stringify `this date. While `stringifying ` this date it remove the space from date and convert it into this given format `2023-10-2314:00:00` (without space). Hence, there's no need for any changes in the code. If we systematically destroy the items, they will appear correctly when we apply the filter of `destroy`.

**Comment by IanMayo** [comment]
But aren't we testing that field for a non-null value? That shouldn't worry about the format.

From the network tab it looks like first we do a non-null filter , then we do a date filter for just one of the dates.

**Comment by TahaKhanAbdalli** [comment]
No it is not working like that. First we find the date against not null field and then apply the filter based on those dates.

**Comment by IanMayo** [comment]
Thanks. Do you understand why we're doing a date filter for 'is destroyed' filter?

**Comment by IanMayo** [comment]
Fixed in #1079
