### ISSUE TITLE
Use `isActive` flag for `Platforms`

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#149]
We have added the `isActive` flag for platforms.

Here is how we should use it:
- in `BatchCreate` filter platforms drop-down for active platforms
- in `BatchList` provided separate filters for `Platform (all)` and `Platform (active)`.
- in `BatchEdit` provide full platforms drop-down (since it may refer to old/inactive platform)
- in `PlatformsList` on reference page, include filter for `isActive` - so maintainer can focus on active platforms, if necessary

Note: the steps above are probably similar to those needed for #140

**Comment by TahaKhanAbdalli** [comment]
I have added filters in `BatchCreate`, `BatchEdit` and `PlatformList`. On the `BatchList` only `active` filter is working, I have attached the screenshot of the documentation which is why I am facing issue applying the all filter. So should I create a draft PR of what I have done till now?

![Screenshot from 2023-04-26 16-31-15](https://user-images.githubusercontent.com/50602678/234562205-ee8d4a62-88cc-434d-8530-59f7f5218ee2.png)

**Comment by IanMayo** [comment]
The `Active Platforms` is just one quick filter.  We can add normal filters for the same source.

Yes, please create a Draft PR.

**Comment by IanMayo** [comment]
Which branch is it, please?

**Comment by TahaKhanAbdalli** [comment]
I haven't pushed the code yet. I am going to create draft PR now.
