### ISSUE TITLE
Date fields mistakenly interpreted as modified in Item Edit

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#425]
I've just edited a `Live Item`, to change the media type.

But, in the audit log, RCO thinks the date fields have changed. They haven't:

![image](https://github.com/DeepBlueCLtd/RCO/assets/1108513/3a6eaaaa-9946-43e6-b8d2-be437885ccc6)

The audit log should record date changes if they are actually changed, but not if they are un-changed.

Steps to reproduce:
- run app
- login as ian/admin
- open Live Items
- open item on second row
- click on `Edit`
- change the media type
- save the item
- re-open item on the second row
- click on view history
- note that start/end dates reported as modified

![image](https://github.com/DeepBlueCLtd/RCO/assets/1108513/0ad17336-4dba-452f-aae8-1f3fa3329a89)

**Comment by TahaKhanAbdalli** [comment]
The issue is `return DateTime.fromJSDate(date1).equals(DateTime.fromJSDate(date2))` this, it does not compare it properly, it works sometimes and sometimes it causes issues. I was thinking of using this ` return new Date(date1).getMilliseconds() === new Date(date2).getMilliseconds()` but it will only compare milliseconds and not timezone etc.

**Comment by IanMayo** [comment]
> The issue is `return DateTime.fromJSDate(date1).equals(DateTime.fromJSDate(date2))` this, it does not compare it properly, it works sometimes and sometimes it causes issues. I was thinking of using this ` return new Date(date1).getMilliseconds() === new Date(date2).getMilliseconds()` but it will only compare milliseconds and not timezone etc.

how about to convert both to ISO date-string, then compare the two values?
