### ISSUE TITLE
Introduce `Edit` for `Departments`

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#954]
Departments aren't expected to get a lot of use.

But, we should provide `Edit` form for the department.

The create and edit pages should allow edit of id, name and active (since sometimes `id` is actually an accepted shortening of the full name)

**Comment by TahaKhanAbdalli** [comment]
In SQLite, the primary key of a table is typically not editable due to the risk of compromising data integrity. It is designed to uniquely identify records, and altering it could lead to conflicts or violations of uniqueness constraints. We recommend maintaining the primary key as an immutable, auto-incrementing value. If there's a need to update identification, consider creating a new record with the desired changes.

**Comment by IanMayo** [comment]
You are exactly right.  

But, we are upgrading a legacy system, and the above pattern was present in the legacy data that we have inherited.

The best I can suggest is that we show a large warning next to the text-control for the `id` field. Something like this:
`Warning: editing the id of a Department that is in use may lead to data corruption.  The id of a department must not be modified if data has been assigned to that department.`

**Comment by TahaKhanAbdalli** [comment]
Hello Ian,
I revisited the SQLite documentation to address the issue. Unfortunately, there is no direct method to modify the primary key in SQLite. If a user attempts to edit the ID, it won't be effective.
To work around this, we can create a new column (named something other than id) in the table where we can store the values like "dept-1," that user sees as ID and can edit. Meanwhile, in SQLite, we can maintain a simple auto-increment primary key id. This way, users can interact with a more user-friendly identifier while the database maintains its efficient numeric primary key system.
This solution is also for issue https://github.com/DeepBlueCLtd/RCO/issues/961
