### ISSUE TITLE
Remove `Delete` from `AddressEdit`

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RCO#959]
We should remove the `Delete` button from the `AddressEdit` page.  It currently (silently) fails.

Aah, this could be useful.  I don't like the fact that it silently fails.

Can we try to catch the error being thrown, and show it in a popup?

Then we should remove the `Delete` button.

**Comment by TahaKhanAbdalli** [comment]
I appreciate the clarification provided regarding this task. If we opt to remove the Delete button, the need to handle errors in a popup becomes irrelevant since the button will be eliminated from the user interface. On the other hand, if the decision is to retain the Delete button in the UI, we will implement the necessary measures to handle errors and display them in a popup. I would appreciate your guidance on the preferred approach for this task?

**Comment by IanMayo** [comment]
I understand the confusion :-)

I'd actually quite like both.  I see logic that fails silently as a significant bug, and want to do all I can to avoid it.

So, I'd first like to catch the error and display it.  Then I'd like to fix the bug.

Aah, the above is only valid if we catch the error at a high level - so we potentially catch a large range of errors.  If we only catch it for this specific instance, and then fix the instance, it will be wasted effort (as you suggest).

Are we able to catch the error at a high level?

**Comment by TahaKhanAbdalli** [comment]
Hello Ian,
I revisited the SQLite documentation to address the issue. Unfortunately, there is no direct method to modify the primary key in SQLite. If a user attempts to edit the ID, it won't be effective.
To work around this, we can create a new column (named something other than id) in the table where we can store the values like "dept-1," that user sees as ID and can edit. Meanwhile, in SQLite, we can maintain a simple auto-increment primary key id. This way, users can interact with a more user-friendly identifier while the database maintains its efficient numeric primary key system.
This solution is also for issue #961
